# エラー対策

In [1]:
l = [1,2,3]
i = 5
l[i]

IndexError: list index out of range

In [2]:
l = [1,2,3]
i = 5
try:
  l[i]
except:
  print('エラーが起きました')

print('処理が終了')

エラーが起きました
処理が終了


In [3]:
l = [1,2,3]
i = 5
try:
  l[i]
except IndexError:
  print('エラーが起きました')

エラーが起きました


In [4]:
l = [1,2,3]
i = 5
try:
  l[i]
except IndexError as ex:
  print(ex)
  print('エラーが起きました')

list index out of range
エラーが起きました


In [5]:
l = [1,2,3]
i = 5
del l
try:
  l[i]
except IndexError as ex:
  print(ex)
  print('エラーが起きました')

NameError: name 'l' is not defined

In [7]:
l = [1,2,3]
i = 5
del l
try:
  l[i]
except IndexError as ex:
  print(ex)
except NameError as ex:
  print(ex)

print('エラーが起きました')

name 'l' is not defined
エラーが起きました


In [8]:
l = [1,2,3]
i = 5
del l
try:
  l[i]
except IndexError as ex:
  print(ex)
except NameError as ex:
  print(ex)
except Exception as ex:
  print(ex)

print('エラーが起きました')

name 'l' is not defined
エラーが起きました


In [9]:
l = [1,2,3]
i = 5
del l
try:
  l[i]
except IndexError as ex:
  print(ex)
except NameError as ex:
  print(ex)
except Exception as ex:
  print(ex)
finally:
  print('エラーが起きました')

name 'l' is not defined
エラーが起きました


# numpy

In [10]:
import numpy as np

In [12]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.shape

(2, 3)

In [16]:
a.ndim

2

In [17]:
a.dtype

dtype('int64')

In [18]:
a.size

6

In [20]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [21]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros((3,4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
a.T

array([0, 1, 2, 3, 4, 5])

In [29]:
a = np.arange(10, 51, 10)
b = np.arange(1, 6)
a + b

array([11, 22, 33, 44, 55])