### Numpyの演算

In [1]:
import numpy as np

n2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

n10 = np.array([
    [1,4,7,10],
    [2,5,8,11],
    [3,6,9,12]
])

print(n2)
print(n10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


### numpyの配列は、([ ])で囲むんですね
→np.array([ ]) の外側の括弧がNumPy関数の引数、内側の括弧が各行のデータを表しています

### 標準偏差を求めてみる
（朝の散歩の途中に調べた）

In [2]:
data = [100, 200, 300, 400, 500]

std = np.std(data)
print(std)

141.4213562373095


In [3]:
n11 = n2 + n10
print(n11)

[[ 2  6 10 14]
 [ 7 11 15 19]
 [12 16 20 24]]


### 揃っていなくても計算できるか
NumPyでは同じ形状の配列でないと算術演算ができません。サイズを揃えるか、部分的な計算を行う必要があります。

In [4]:
n00 = np.array([1,2,3,4,5])
n01 = np.array([1,2,3])

print(n00 + n01)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### ブロードキャスト機能
→NumPyで異なるサイズの配列同士でも計算を可能にする仕組み
（配列の各要素に対して同じ計算を行うため）

In [5]:
n00 = np.array([1,2,3,4])
num = 10

print(n00 + num)

[11 12 13 14]


In [7]:
n00 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

n01 = np.array([10,10,30,40])

print(n00 + n01)

[[11 12 33 44]
 [15 16 37 48]]


### サイズが合わないモノは計算できないので注意

In [8]:
n1 = np.array([1,7,5,2])

print(n1)

[1 7 5 2]


In [9]:
print(n1-4)

[-3  3  1 -2]


In [11]:
n2= np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(n2-2)

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


### 集約関数

In [13]:
n2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(n2.sum())

78


### 行方向と列方向に集約する

In [14]:
print(n2.sum(axis=0))
print(n2.sum(axis=1))

[15 18 21 24]
[10 26 42]
