In [4]:
import numpy as np

### これだと通常のリストになってしまう

In [9]:
n1 = ([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(n1)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [11]:
print(n1[1][2])

7


### これだと3次元のリストになってしまう

In [12]:
n = [[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]]

print(n)

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]


### 2次元にするにはこうする

In [13]:
n = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

print(n)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


### これはタプルですか？
いいえ、これはリストです。タプルではありません。
外側の()は数学の括弧と同じで、単なるグルーピングです。

この2つは全く同じ意味
n1 = ([1, 2, 3])
n2 = [1, 2, 3]

print(type(n1))   # <class 'list'>
print(type(n2))   # <class 'list'>

In [ ]:
### これでNumpayのarray（配列）になった

In [14]:
n2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(n2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 指定して出力できる

In [15]:
n5 = n2[1,2]
print(n5)

7


In [16]:
n6 = n2[1, :]
print(n6)

[5 6 7 8]


In [18]:
n7 = n2[:, 0]
print(n7)

[1 5 9]


In [19]:
n8 = n2[:2, 2:]
print(n8)

[[3 4]
 [7 8]]


In [20]:
n2_index = np.array([True, True, False])
n9 = n2[n2_index]
print(n9)

[[1 2 3 4]
 [5 6 7 8]]
