In [1]:
import numpy as np

In [2]:
x = np.array([2/7, 1000/7, 0.034567])
print(x)

[2.85714286e-01 1.42857143e+02 3.45670000e-02]


### 表示形式を変更

In [3]:
np.set_printoptions(
    suppress=True,
    precision=4,
    floatmode='fixed'
)
print(x)

[  0.2857 142.8571   0.0346]


In [4]:
nl = np.array([1,7,5,2])
print(nl)

[1 7 5 2]


In [6]:
# 型を確認
print(type(nl))

# 要素数
print(nl.shape)

# 長さ
print(len(nl))

<class 'numpy.ndarray'>
(4,)
4


### numpuのarray関数は配列を作るんですよね？
NumPyの`array()`関数は配列（ndarray）を作成する関数です。

## 基本的な使い方

```python
import numpy as np

# リストから配列を作成
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # [1 2 3 4 5]

# 2次元配列を作成
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# [[1 2 3]
#  [4 5 6]]
```

## PythonのリストとNumPy配列の違い

```python
# Pythonのリスト
python_list = [1, 2, 3, 4, 5]

# NumPy配列
numpy_array = np.array([1, 2, 3, 4, 5])

print(type(python_list))   # <class 'list'>
print(type(numpy_array))   # <class 'numpy.ndarray'>
```

## NumPy配列の利点

1. **高速な計算**
```python
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2  # 全要素を2倍
print(result)     # [ 2  4  6  8 10]
```

2. **便利な数学関数**
```python
arr = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr)  # 平方根
print(sqrt_arr)          # [1. 2. 3. 4. 5.]
```

つまり、`np.array()`は**リストやタプルなどをNumPyの高性能な配列に変換する**関数です！

### 2次元の表を作る

In [7]:
n2 = np.array(
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
)

print(n2)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

### 2重構造のリストにならないとエラーになる

In [8]:
n2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(n2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# こっちはプロパティ
print(n2.shape)

# こっちは関数
print(len(n2))

(3, 4)
3


### 等間隔の数値配列

In [10]:
n3 = np.linspace(0,2,11)

print(n3)

[0.0000 0.2000 0.4000 0.6000 0.8000 1.0000 1.2000 1.4000 1.6000 1.8000
 2.0000]


### linspaceってどういう意味？
linspaceは**「linear space（線形空間）」の短縮形で、「等間隔に並んだ数値の配列を作成する」**NumPy関数です。

In [12]:
n4 = np.arange(0, 2.2, 0.2)

print(n4)

[0.0000 0.2000 0.4000 0.6000 0.8000 1.0000 1.2000 1.4000 1.6000 1.8000
 2.0000]
