In [1]:
import numpy as np

# 配列の各要素を比較する（1か所だけ違う）

In [4]:
yt = np.array([1,1,0,1,0,1,1,0,1,1])
yp = np.array([1,1,0,1,0,1,1,1,1,1])

print(yt)
print(yp)

[1 1 0 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 1 1]


# True/Falseの配列が返ってくる

In [5]:
matched = (yt == yp)
print(matched)

[ True  True  True  True  True  True  True False  True  True]


# Trueは1、Falseは0になることを利用

In [6]:
correct = matched.sum()

print(correct)

9


In [7]:
total = len(matched)

print(total)

10


In [8]:
accuracy = correct / total

print(accuracy)

0.9


# 最大値と最小値を調べたい

In [9]:
nl = np.array([1,7,5,2])
print(nl)

[1 7 5 2]


最大値と最小値で正規化する

In [10]:
nl_max = nl.max()
nl_min = nl.min()

print(nl_max)
print(nl_min)

7
1
